### ISSUE TITLE
Connection got RemoteDisconnected, retrying...

### ISSUE THREAD

**Issue by DiameterEffect** [Benjins/Anarchivist#1]
Is there anyway i can fix this? It keeps shwoing me this RemoteDisconnected, and then after a few minutes it gives me "added 100 tweets.."
Info:
Im using the latest version of this tool.
OS:Windows 10

**Comment by Benjins** [comment]
Occasionally the connection fails and it needs to reconnect, so if you only see "Connection got RemoteDisconnected, retrying..." every so often it should be fine.
There's unfortunately not much other feedback, the "added 100 tweets" is only printed after actually getting all the tweets and their data. If there are a lot of images and videos to download, then those 100 tweets might take a while. If the app is still running, and printing out "added 100 tweets" every so often then there shouldn't be a problem (although you can check the data it downloads on disk to be sure)

**Comment by DiameterEffect** [comment]
> Occasionally the connection fails and it needs to reconnect, so if you only see "Connection got RemoteDisconnected, retrying..." every so often it should be fine.
> There's unfortunately not much other feedback, the "added 100 tweets" is only printed after actually getting all the tweets and their data. If there are a lot of images and videos to download, then those 100 tweets might take a while. If the app is still running, and printing out "added 100 tweets" every so often then there shouldn't be a problem (although you can check the data it downloads on disk to be sure)

 I was just concerned because i thought my vpn was missing with this tool.Thank you once again!
closing!
