### ISSUE TITLE
Resolution of Twitter photos

### ISSUE THREAD

**Issue by JohnQuincyAddingMachine** [Benjins/Anarchivist#2]
I notice that, for photos, the script is grabbing **/media/blahblahblah.jpg**, which maxes out at 1200x1200 or so. If it grabbed **/media/blahblahblah.jpg?name=4096x4096** or **/media/blahblahblah.jpg?name=orig**, it'd get the full resolution image instead. Is it possible for the script to be modified to work that way?

**Comment by Benjins** [comment]
Yeah, probably. Unfortunately, Twitter doesn't give any full-resolution URL in the JSON it returns, so it would need to be hard-coded to use `name=orig`, which may stop working at some point in the future. But I can modify the script for now

**Comment by Benjins** [comment]
Should be fixed by latest commit (2fca34acd95dcff0b00678f2b827c0f7c9a510f7)

**Comment by JohnQuincyAddingMachine** [comment]
Ah, that works perfectly. Thank you so much!
